kind: ServiceAccount
apiVersion: v1
metadata:
  name: ambassador-service-account
  namespace: ambassador-poc
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ambassador-role
rules:
  - apiGroups: [""]
    resources:
    - services
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  - apiGroups: [""]
    resources:
    - secrets
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ambassador-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ambassador-role
subjects:
  - name: ambassador-service-account
    namespace: ambassador-poc
    kind: ServiceAccount
    