# https://docs.bitnami.com/kubernetes/how-to/configure-rbac-in-your-kubernetes-cluster/
kind: Namespace
apiVersion: v1
metadata:
  name: ambassador-poc
  labels:
    name: ambassador-poc
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ambassador-poc-admin
  namespace: ambassador-poc
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: helm
  namespace: ambassador-poc
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: test-user
  namespace: ambassador-poc
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-binding
  namespace: ambassador-poc
subjects:
- kind: ServiceAccount
  name: helm
  namespace: ambassador-poc
roleRef:
  kind: Role
  name: ambassador-poc-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-user-binding
  namespace: ambassador-poc
subjects:
- kind: ServiceAccount
  name: test-user
  namespace: ambassador-poc
roleRef:
  kind: Role
  name: ambassador-poc-admin
  apiGroup: rbac.authorization.k8s.io
